### ISSUE TITLE
Using site-env as part of the DMOJ docs

### ISSUE THREAD

**Issue by Xyene** [Minkov/dmoj-env#1]
Hi,

I'm one of the core developers of the DMOJ platform.

We were looking at providing a Vagrant setup for the site and all related services (PDF rendering, math/LaTeX servers, camo, etc.) so that potential contributors don't have the (large) hurdle of installing the site from scratch.

So, we were wondering if we could use your setup here as a base to work off of (since it works 😄). We'd be happy to keep your current license.

**Comment by Minkov** [comment]
Hello,

You can use it as you please :)

I have also a partial docker setup, if you are interested :)
 - [docker-compose.yml](https://github.com/Minkov/site/blob/telerikacademy/docker-compose.yml) and [Dockerfile](https://github.com/Minkov/site/blob/telerikacademy/Dockerfile)

**Comment by Xyene** [comment]
Thanks!

We also have a [partial Docker](https://github.com/DMOJ/site-docker) that works but isn't production-ready; will definitely take a look at yours too and hopefully come up with something usable.
